apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: registry.redhat.io/rhel8/postgresql-13
        name: db-pod
        command: ["/bin/sh"]
        args:
          - ["wget", "https://github.com/schmts/nalogec/blob/main/init.sql"]
          - ["cp", "init.sql", "/docker-entrypoint-initdb.d/"]
    envFrom:
      - secretRef:
        name: db-secret
    
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  app: postgres
  type: db
spec:
  type: ClusterIp
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: postgres
    type: db
  
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  POSTGRESQL_USER: cG9zdGdyZXNVc2Vy
  POSTGRESQL_PASSWORD: cG9zdGdyZXNQVw==
  POSTGRESQL_DATABASE: bmFsb2dh

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-networkpolicy
spec:
  podSelector:
    matchLabels:
      type: db
---
