---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    name: fe-deployment
    type: frontend
spec:
  containers:
    name: fe-pod
    image: quay.ts.telekom.si/learning/jrejec/app-fe:1.0.0
  envFrom:
      - secretRef:
        name: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec: 
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      Nodeport: 30000
  selector:
    type: frontend

---
apiVersion:
kind:
metadata:
spec:
---
apiVersion:
kind:
metadata:
spec:
---
apiVersion:
kind:
metadata:
spec:
---
