apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    name: fe-deployment
    
spec:
  template:
    metadata:
      labels:
        name: fe-deployment
    spec:      
      containers:
        - name: fe-pod
          image: quay.ts.telekom.si/learning/jrejec/app-fe:1.0.0
          #image: jrejec/app-fe:1.0.0
          #imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: db-configmap
  replicas: 1
  selector:
    matchLabels:
      name: fe-deployment          
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  clusterIP: 10.99.138.44
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30000
  selector:
    name: fe-deployment

---
